version: '3'
services:
  mongodb:
    image: mongo
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build:
      context: ./backend/
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

    

